### ISSUE TITLE
Missing Width_Extender module

### ISSUE THREAD

**Issue by rodrigomelo9** [laforest/FPGADesignElements#11]
Hi @laforest. The module `Width_Extender` is referenced in some other modules such as `Adder_Subtractor_Binary_Saturating.v` and `Adder_Subtractor_Binary.v`, but is not in the repository.

**Comment by laforest** [comment]
Ah. Whoops. Wrong module name. Replaced with instance of more general Width_Adjuster. Thanks for spotting this!
