### ISSUE TITLE
CAM implementation

### ISSUE THREAD

**Issue by pwang7** [laforest/FPGADesignElements#18]
Hi there, I'm looking for a CAM implementation, the "FPGA Design Elements" is lack of CAM related content.
Would you please kindly share with me some resource/documents on CAM?
Thanks!

**Comment by laforest** [comment]
Hello,
I haven't implemented any CAM logic yet. If you would like to design your own, start with "Deep and narrow binary content-addressable memories using FPGA-based BRAMs", by Abdelhadi and Lemieux: https://ieeexplore.ieee.org/abstract/document/7082808
Good Luck!
Eric

**Comment by pwang7** [comment]
> Hello, I haven't implemented any CAM logic yet. If you would like to design your own, start with "Deep and narrow binary content-addressable memories using FPGA-based BRAMs", by Abdelhadi and Lemieux: https://ieeexplore.ieee.org/abstract/document/7082808 Good Luck! Eric

Thank you so much!
