### ISSUE TITLE
Consider deploying to github pages

### ISSUE THREAD

**Issue by sajattack** [laforest/FPGADesignElements#2]
It would increase the accessibility of your book and it's not very hard to set up.

**Comment by JarrettR** [comment]
Agreed.
In the meantime, it also seems to be hosted here: http://fpgacpu.ca/fpga/index.html

**Comment by laforest** [comment]
Thanks for the suggestion (I did not know about github pages), but I already have my own hosting, and the web pages are simply the git repo itself. I have added a link to the website in the README. (I plain forgot!)
